def standardizeLocations(f):
    f['Standardized Location'] = f['Location Type']
    print('start', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"RESIDENTIAL BUILDING","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Sidewalk","Street/Sidewalk"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Residential Building/House","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Club/Bar/Restaurant","Restaurant/Bar/Deli/Bakery"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"3+ Family Apt. Building","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"1-2 Family Dwelling","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Street/Curbside","Street"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Residential Building","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"1-, 2- and 3- Family Home","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Comercial","Store/Commercial"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Other (Explain Below)","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"3+ Family Apartment Building","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Commercial Building","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Co-Op Unit","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Residential","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Curb","Street/Curbside"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"3+ Family Mixed Use Building","Mixed Use"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Above Address","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Condo Unit","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Vacant Lot","Lot"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Address Outside of NYC","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"1-2 Family Mixed Use Building","Mixed Use"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Address","Property Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Caller Address","Property Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public/Unfenced Area","Public Area"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Parking Lot/Garage","Lot"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Residential Property","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Commercial","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Senior Center","Senior Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Residence","Residential"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Street Area","Street"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Restaurant","Restaurant/Bar/Deli/Bakery"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Apartment Building","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Catch Basin/Sewer","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Street and Sidewalk","Street"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"House and Store","Mixed Use"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Food Cart Vendor","Mobile Food Vendor"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Apartment","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Green Cart Vendor","Mobile Food Vendor"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"P.O. Box","Other"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Private House","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Tattoo Parlor","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Garden","Park"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Common Area","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Parking Lot","Lot"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Catering Service","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Store","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Single Room Occupancy (SRO)","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Private School","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Park/Garden","Park"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Street Vendor","Mobile Food Vendor"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Day Care/Nursery","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Garden/Park","Park"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Abandoned Building","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School/Pre-School","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Office Building","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Building","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Subway Station","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Other (explain in Complaint Details)","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Street Address","Street"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"1-3 Family Dwelling","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Vacant Lot/Property","Lot"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Garage","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Soup Kitchen","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Spa Pool","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cafeteria - Public School","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cafeteria - College/University","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Speed Reducer","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Roof","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Pvt Residnt Proprty","Residential"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Groomer","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Stairs","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Grocery Store","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Hospital","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School Safety Zone","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cafeteria - Private School","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Commercial Property","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Private Residence","Residential"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Airport or Train/Bus Station","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public School","School"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Street Fair Vendor","Mobile Food Vendor"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Homeless Shelter","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Golf","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Swamp or Pond","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Service Provider","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Medical Facility","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School - K-12 Public","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Vacant Land","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Petting Zoo/Animal Exhibit","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Sauna","Store/Commercial"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Steam Room","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Ground","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Theater","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School - K-12 Private","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"1-3 Family Mixed Use Building","Mixed Use"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School - College/University","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Tire Shop","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Sports Arena","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Permanent Food Stand","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Wooded Area","Other"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Nursing Home","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cafeteria - Private","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Correctional Facility - City","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Tanning Salon","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Summer Camp","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Doctor's Office","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Nail Salon","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Building-Wide","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Plaza","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cemetery","Other"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Veterinarian's Office","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Cafeteria","Restaurant/Bar/Deli/Bakery"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Public Area","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Pier","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Horse Stable","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Dentist's Office","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Correctional Facility - State","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Health Club","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Retail Store","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Street/Sidewalk","Street/Sidewalk"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Street","Street"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Store/Commercial","Store/Commercial"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Park","Park"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Property Address","Property Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Restaurant/Bar/Deli/Bakery","Restaurant/Bar/Deli/Bakery"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Senior Address","Senior Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Lot","Lot"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"NYC Street Address","NYC Street Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Mixed Use","Mixed Use"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Park/Playground","Park/Playground"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Highway","Highway"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Other","Other"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"School","School"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Mobile Food Vendor","Mobile Food Vendor"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Bike Lane","Bike Lane"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Bus Stop Shelter","Bus Stop Shelter"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"DRIE Tenant's Address","DRIE Tenant's Address"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Building (Non-Residential)","Building (Non-Residential)"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"House of Worship","House of Worship"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Construction Site","Construction Site"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Taxi","Taxi"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Ferry","Ferry"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Government/Not-for Profit","Government/Not-for Profit"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Bridge","Bridge"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Beach","Beach"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Crosswalk","Crosswalk"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Recreation Center","Recreation Center"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Vacant Building","Vacant Building"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Pool","Pool"	, f['Standardized Location'])
    print('>', end = '')
    f['Standardized Location']=np.where(f['Location Type']==	"Address Unknown","Address Unknown"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Bridge/Underpass","Bridge/Underpass"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Overpass","Overpass"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Terminal","Terminal"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Hallway","Hallway"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Stairwell","Stairwell"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Vehicle Lane","Vehicle Lane"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Government Building","Government Building"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Lobby","Lobby"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Kennel/Animal Shelter","Kennel/Animal Shelter"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Subway","Subway"	, f['Standardized Location'])
    f['Standardized Location']=np.where(f['Location Type']==	"Roadway Tunnel","Roadway Tunnel"	, f['Standardized Location'])
    print('END')
